baseURL = "https://udesh.io" # Replace with your domain
languageCode = "en-us"
title = "udesh"
theme = "PaperMod"
summaryLength = 50
paginate = 10

# Author information
[author]
  name = "Udesh"
  website = "https://udesh.io"

# Menu Configuration
[menus]

  [[menus.main]]
    identifier = "home"
    name = "home"
    pageRef = "/"
    weight = 1

  [[menus.main]]
    identifier = "podcast"
    name = "podcast"
    url = "https://onedeeper.substack.com"
    weight = 3

  [[menus.main]]
    identifier = "personal"
    name = "writing/personal"
    pageRef = "/personal"
    weight = 4

  [[menus.main]]
    identifier = "academic"
    name = "writing/academic"
    pageRef = "/academic"
    weight = 5

  [[menus.main]]
    identifier = "misc"
    name = "projects"
    pageRef = "/misc"
    weight = 6

  [[menus.main]]
    identifier = "centenarian"
    name = "centenarian decathlon"
    url = "/centenarian.html"
    weight = 7

# Parameters for the PaperMod theme
[params]

  logo = "images/logo.png" # Add a logo in your "static/images" directory
  themeColor = "#FF370C" # Customize to match your preferred brand color
  mode = "light" # Options: "light", "dark", "auto"
  customCSS = ["css/extended/tufte.css"]

  ShowReadingTime = true # Display estimated reading time for posts
  ShowShareButtons = false # Enable sharing buttons on posts
  ShowBreadCrumbs = false
  ShowProjectsPage = false # Add this line to disable showing projects on the homepage
  mainSections = ["personal"]
  disableThemeToggle = true